# Generated by Django 4.1.4 on 2023-01-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='landdetail',
            fields=[
                ('land_id', models.AutoField(primary_key=True, serialize=False)),
                ('land_name', models.CharField(default='', max_length=100)),
                ('land_dimension', models.CharField(default='', max_length=100)),
                ('land_ph', models.CharField(default='', max_length=100)),
                ('land_area', models.CharField(default='', max_length=100)),
                ('land_nitrogen', models.CharField(default='', max_length=100)),
                ('land_phosphorous', models.CharField(default='', max_length=100)),
                ('land_pottassium', models.CharField(default='', max_length=100)),
                ('land_sulphur', models.CharField(default='', max_length=100)),
                ('land_calcium', models.CharField(default='', max_length=100)),
                ('land_magnesium', models.CharField(default='', max_length=100)),
                ('land_typeLand', models.CharField(default='', max_length=100)),
                ('land_typeirrigation', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
