# Generated by Django 4.1.4 on 2023-01-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_landdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='farmerdetail',
        ),
        migrations.AddField(
            model_name='landdetail',
            name='farmer_address1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='landdetail',
            name='farmer_city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='landdetail',
            name='farmer_email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='landdetail',
            name='farmer_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='landdetail',
            name='farmer_phone',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='landdetail',
            name='farmer_state',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='landdetail',
            name='farmer_zip',
            field=models.CharField(default='', max_length=100),
        ),
    ]
