# Generated by Django 4.1.4 on 2023-01-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0004_farmerdetail_remove_landdetail_farmer_address1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landdetail',
            name='generated_id',
            field=models.CharField(default='', max_length=60),
        ),
    ]
