# Generated by Django 4.1.4 on 2023-01-07 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0007_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='log_sign',
        ),
    ]
