# Generated by Django 4.1.4 on 2023-01-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0008_rename_user_log_sign'),
    ]

    operations = [
        migrations.AddField(
            model_name='landdetail',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
