# Generated by Django 4.1.4 on 2023-01-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0009_landdetail_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='landdetail',
            name='land_crop',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='landdetail',
            name='land_survey',
            field=models.CharField(default='', max_length=100),
        ),
    ]
