# Generated by Django 4.1.4 on 2023-01-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0010_landdetail_land_crop_landdetail_land_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerdetail',
            name='username',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='landdetail',
            name='land_survey',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='landdetail',
            name='username',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
