# Generated by Django 4.1.4 on 2023-01-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0013_transporttruck'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporttruck',
            name='t_payment',
            field=models.CharField(default='', max_length=50),
        ),
    ]
