# Generated by Django 4.1.4 on 2023-01-23 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0016_alter_contact_cemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='cemail',
            field=models.EmailField(default=True, max_length=50),
        ),
    ]
