# Generated by Django 4.1.4 on 2023-01-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0017_alter_contact_cemail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log_sign',
            name='id',
        ),
        migrations.AlterField(
            model_name='log_sign',
            name='username',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
