# Generated by Django 4.1.4 on 2023-01-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0018_remove_log_sign_id_alter_log_sign_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='caddress',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='ccrop',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='cemail',
            field=models.EmailField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='cname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='cnumber',
            field=models.CharField(default='', max_length=50),
        ),
    ]
