# Generated by Django 4.1.4 on 2023-01-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0019_alter_contact_caddress_alter_contact_ccrop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='cemail',
            field=models.CharField(default='', max_length=50),
        ),
    ]
