# Generated by Django 4.1.4 on 2023-01-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0021_alter_contact_cemail_alter_landdetail_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landdetail',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
