# Generated by Django 4.1.4 on 2023-01-26 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0022_alter_landdetail_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='cemail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.log_sign'),
        ),
        migrations.AlterField(
            model_name='farmerdetail',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.log_sign'),
        ),
        migrations.AlterField(
            model_name='landdetail',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.log_sign'),
        ),
        migrations.AlterField(
            model_name='transporttruck',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.log_sign'),
        ),
    ]
