# Generated by Django 4.1.4 on 2023-01-26 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0023_alter_contact_cemail_alter_farmerdetail_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landdetail',
            name='land_name',
        ),
    ]
