# Generated by Django 4.1.4 on 2023-01-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0025_alter_farmerdetail_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landdetail',
            name='land_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
