# Generated by Django 4.1.4 on 2023-01-26 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0026_landdetail_land_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerdetail',
            name='farmer_email',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='log_sign',
            name='username',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
