# Generated by Django 4.1.4 on 2023-01-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='transport',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(default='', max_length=50)),
                ('company_slogan', models.CharField(default='', max_length=50)),
                ('company_description', models.CharField(default='', max_length=50)),
                ('truck_image', models.CharField(default='', max_length=50)),
                ('crops_transport_provided', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
