# Generated by Django 4.1.4 on 2023-01-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='company_logo',
            field=models.ImageField(default='', upload_to='transport/images/'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='company_name',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
