# Generated by Django 4.1.4 on 2023-01-15 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_alter_transport_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='company_logo',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
