# Generated by Django 4.1.4 on 2023-01-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_alter_transport_company_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='transporttruck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(default='', max_length=50)),
                ('username', models.CharField(default='', max_length=50)),
                ('t_Email', models.CharField(default='', max_length=50)),
                ('t_phone', models.CharField(default='', max_length=50)),
                ('t_from', models.CharField(default='', max_length=50)),
                ('t_where', models.CharField(default='', max_length=50)),
                ('t_date', models.DateField(default='')),
                ('t_weight', models.CharField(default='', max_length=50)),
                ('t_message', models.CharField(default='', max_length=50)),
                ('t_price', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='transport',
        ),
    ]
