# Generated by Django 4.1.4 on 2023-01-18 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0005_transporttruck_delete_transport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='transporttruck',
        ),
    ]
