# Generated by Django 4.1.4 on 2023-01-21 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0007_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporttruck',
            name='t_genereted_id',
            field=models.CharField(default='', max_length=10),
        ),
    ]
