# Generated by Django 4.1.4 on 2023-01-21 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0008_transporttruck_t_genereted_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='transporttruck',
        ),
    ]
